### ISSUE TITLE
Awesome! Thanks - Consider using a less-used port than 3000?

### ISSUE THREAD

**Issue by rfay** [torenware/ddev-viteserve#1]
Thanks so much for sharing this!

Would you consider using a port other than 3000? Every single node-based project wants to use 3000, so it makes them all incompatible with each other...

**Comment by torenware** [comment]
Yeah, hear you about 3000. But unfortunately, ViteJS happens to be part of that thundering herd :-)  So this one’s above my (not so cosmic) pay grade.

It *is* configurable in vite.config.js, but the user needs to know that. Best way to deal with this is to make this another settable parameter for users of the add-on.

R

**Comment by torenware** [comment]
I think the best way to handle this is to make it easily configurable and better documented.

Ideally, you'd want to get the vite port configuration out of the vite config file; but that file can contain arbitrary javascript, and typically loads other javascript modules. So the DDEV related settings need to match that.  Right now, documentation is the main way to make sure that people match the DDEV settings to what vite.config.js is actually doing.

I'll look at the docs (perhaps even today) to see what I can do with that. I'll also see if the add-on can "ping" the dev server to make sure it is actually on the expected port.

**Comment by mandrasch** [comment]
Just fiy: In vite version 3 they changed the default port:

> the default dev server port is now 5173 and the preview server listening at 4173. This change ensures Vite will avoid collisions with other tools.
https://vitejs.dev/blog/announcing-vite3.html#dev-improvements

**Comment by torenware** [comment]
Hopefully drud/ddev#3598 will land soon, so I can make it easier to change this.  Happy for the Vite people that they got Vite 3 done in any case.  This will make @rfay happy, at the very least (#1)

**Comment by torenware** [comment]
Vite 3 support is now in, and 5173 is the new default port. It's configurable, however.  I've confirmed that both the dev server and HMR work out of the box with the standard settings.

**Comment by rfay** [comment]
Cool.
