### ISSUE TITLE
Please remove ddev-get "topic"

### ISSUE THREAD

**Issue by rfay** [torenware/ddev-viteserve#26]
Hi @torenware - It looks like this isn't getting any love at this point. Could you please remove the "ddev-get" label from it so it doesn't get discovered by people looking for a maintained add-on? 

Thanks!

Thanks for exploring this territory. 

If you think it would be good to archive this repo, please do that after adding a link on the top of the README to https://ddev.com/blog/working-with-vite-in-ddev/

**Comment by torenware** [comment]
Sorry for the delay in handling this; I've been unable to give time to this project for some time, as you've figured. I've removede the topic, and will update the read-me once I'm settled on this new laptop.
