### ISSUE TITLE
[feat] Support npm and yarn?

### ISSUE THREAD

**Issue by mandrasch** [torenware/ddev-viteserve#3]
Hey, 

just as suggestion for improvement:

Is it possible that the following can be also switched to use `npm` or `yarn`?

```sh
  # make sure node_modules has linux and not mac code:
  cd $VITE_DIR
  pnpm install
```
https://github.com/torenware/ddev-viteserve/blob/master/commands/web/vite-serve#L20

Arguments:

- users may have run `ddev exec npm install` or `ddev exec yarn install` already in their repo
- pnpm is catching up, but many projects still use npm/yarn https://npmtrends.com/npm-vs-pnpm-vs-yarn
- as far as I know `pnpm` has some differences to npm/yarn, there might be incompatibilies? (not an expert on this)

Cheers,
Matthias

**Comment by torenware** [comment]
Why?  No reason to.  You can use anything you like when you develop locally.  I'm simply calling `* install` inside the container to make sure that it gets run.  YOU DO NOT NEED TO ALSO RUN IT!!!!!

There is no reason to run it yourself. In fact, please don't!!

**Comment by torenware** [comment]
> Is it possible that the following can be also switched to use `npm` or `yarn`?
> 
> ```shell
>   # make sure node_modules has linux and not mac code:
>   cd $VITE_DIR
>   pnpm install
> ```
> 

This is what is called an "implementation detail".  The main reason to prefer pnpm is that it's much faster, especially after it's run the first time. yarn is *very* slow, pretty much every time you run. npm is not much better, although it's less noisy when it runs.

The main point is that when any of these are run under ddev, they will be linux compatible. To allow you run locally and share the same node_modules directory does not appear to be possible.  If I could, I would not mirror node_modules at all. So the simplest thing to do is to make sure it's run, by running it.

If you decide to run yarn or npm after I've run pnpm, it will likely work fine. But there is ABSOLUTELY NO REASON TO DO IT. 

> 
> Arguments:
> 
>     * users may have run `ddev exec npm install` or `ddev exec yarn install` already in their repo
> 

If they are saving node_modules into their repos, this is very much NOT RECOMMENDED EVER. Not under DDEV. Nor any other circumstances.

>     * pnpm is catching up, but many projects still use npm/yarn https://npmtrends.com/npm-vs-pnpm-vs-yarn
> 

Not really relevant.

>     * as far as I know `pnpm` has some differences to npm/yarn, there might be incompatibilies? (not an expert on this)
>

It's close enough for purposes of running it from inside of the container.

**Comment by tyler36** [comment]
An option would be nice.

- By using PNPM, this addon ignores the NPM `package.lock` or yarn `yarn.lock` potenitial installing different versions.
- If my prefered manager is NPM, what should I do with `pnpm-lock.yaml`? Commit it? This is the same problem as above but in reverse.
- After running this, I also have 3k+ files in a `.pnpm-store` directory. Eg.  `.pnpm-store/v3/files/00/0af4fc03d2ecf7155b911e07941ea071519cc573fc911548cdad0701587a3617d6dc9954610260c3d1c421adc4799ccec5835ec14b994d5fc5baa8a6f83e0a`. Are these needed to run the vite server? I assume they are a cache of sorts.

**Comment by torenware** [comment]
> On Aug 3, 2022, at 6:26 PM, tyler36 ***@***.***> wrote:
> 
> 
> An option would be nice.
> 
> By using PNPM, this addon ignores the NPM package.lock or yarn yarn.lock potenitial installing different versions.
That is the one thing that has some validity.
> If my prefered manager is NPM, what should I do with pnpm-lock.yaml? Commit it? This is the same problem as above but in reverse.
Best to commit that, if you want to lock down versions.
> After running this, I also have 3k+ files in a .pnpm-store directory. Eg. .pnpm-store/v3/files/00/0af4fc03d2ecf7155b911e07941ea071519cc573fc911548cdad0701587a3617d6dc9954610260c3d1c421adc4799ccec5835ec14b994d5fc5baa8a6f83e0a. Are these needed to run the vite server? I assume they are a cache of sorts.
That directory should be .gitignore. pnpm symlinks into that cache so that node_modules works as normal.  You want the directory to be up there because it really turbocharges startup of Vite-serve. But you do not want the directory in your repo.

In general, this is indeed an implementation detail. I’m open to a PR that makes it a setting, but it really isn’t a great use of time as feature.  If you really need to lock down versions, make sure that pnpm-lock.json gets saved.  All you need to do. 

The alternative is to not call it, and that has stability issues; bad binaries can crash the software. 

R

**Comment by tyler36** [comment]
Thank you for the feedback. 

I agree with you. Version discrepency being my main concern. The devil is in the details when you are debugging issues. I've been bitten by this problem before.

I think once we have the addon in "production-ready" state, we can look at adding extending it with NPM / Yarn support, if there is demand.

**Comment by mandrasch** [comment]
Hey @torenware, thanks for the super quick feedback on this! Thanks @tyler36 for also jumping in on this!

>  By using PNPM, this addon ignores the NPM package.lock or yarn yarn.lock potenitial installing different versions.

This is my main concern.

As far as I know `package-lock.json` should be also commited to git. Github Action Pipelines and CI/CD tools also use it as reference for the final build/deployment.

> The goal of package-lock.json file is to keep track of the exact version of every package that is installed so that a product is 100% reproducible in the same way even if packages are updated by their maintainers.
Source: https://nodejs.dev/learn/the-package-lock-json-file

> The package-lock.json file needs to be committed to your Git repository, so it can be fetched by other people, if the project is public or you have collaborators, or if you use Git as a source for deployments.
Source: https://nodejs.dev/learn/the-package-lock-json-file

Yarn has it's own `yarn.lock` as well (https://classic.yarnpkg.com/lang/en/docs/yarn-lock/)

Since DDEV has support for `ddev npm` and `ddev yarn` and teams make decision about what to use in a development project, I'll would assume it should be a core feature to switch this. At least in my humble opinion. 

Don't want to disturb your work. 

I just added this issue because ddev-viteserve will maybe (hopefully) become the default recommended plugin for vite + DDEV? Would be awesome if DDEV users had a quick way of using vite with your plugin and I fear forcing `pnpm` could be a deal-breaker for some development teams and projects. 

Much much respect for your hard work on this!

**Comment by torenware** [comment]
I've added support for this in release 0.2.5 as an "experimental feature".  The add-on now recognizes the variable in .ddev/.env of `VITE_JS_PACKAGE_MGR`; the default is `pnpm`, but you should be able to substitute 

```env
VITE_JS_PACKAGE_MGR=npm
```

or

```env
VITE_JS_PACKAGE_MGR=yarn
```

I don't currently have a test for this (hence, experimental) but it should work for any package manager that is (1) actually present in the web container, and (2) has an install command.  Since yarn and npm are pre-installed, they should both work.

The code currently makes sure that the command exists, and if it does not, exits with an error. It will call the package manager specified if it does exist.  Or should, anyway.  YMMV.

**Comment by torenware** [comment]
As of Release 0.3.0, this is completely implemented.  Closing.

**Comment by mandrasch** [comment]
Awesome, thanks very much! 🎉
