### ISSUE TITLE
Support Installation as an Add-on

### ISSUE THREAD

**Issue by kerns** [torenware/ddev-viteserve#4]
Could ddev-viteserve support installation as an add-on via `ddev config`? Maybe this is up to ddev config, or is already possible and I just don't know how to achieve it. Feel free to close this, I think jumped the gun.

What I want is something like... 

```
ddev config --project-type=laravel --docroot=public --php-version=8.1 --add-on=torenware/ddev-viteserve
```

**Comment by rfay** [comment]
It already is a DDEV add-on, see the readme :) It was developed as an add-on :)

**Comment by kerns** [comment]
I understood this a few seconds after I posted the issue and felt bad about it of course, worse bc my confusion was multi-layered. I actually misunderstood add-ons to be a way of taking packages and making them available to ddev's cli, so they could be installed with a flag on `ddev config` ...but this doesn't seem like a thing that is even possible.

All of this to say, this issue is even dumber than it looks. 🤦🏻‍♂️ Moving on! :)

**Comment by torenware** [comment]
> I understood this a few seconds after I posted the issue and felt bad about it of course, worse bc my confusion was multi-layered. I actually misunderstood add-ons to be a way of taking packages and making them available to ddev's cli, so they could be installed with a flag on `ddev config` ...but this doesn't seem like a thing that is even possible.
> 
> All of this to say, this issue is even dumber than it looks. 🤦🏻‍♂️ Moving on! :)

Not a problem. Mistakes? We all make 'em
