### ISSUE TITLE
Warning about missing package manager variable

### ISSUE THREAD

**Issue by Furo42** [torenware/ddev-viteserve#9]
When I startup a project that has vite-serve included I get the following warning each time:

`The \"VITE_JS_PACKAGE_MGR\" variable is not set. Defaulting to a blank string.`

If I add the variable with an empty string .env the message disappears.

Is this intended?
vite-serve's auto dectection works very fine for me so I don't understand why I should still add a variable with no content?

**Comment by torenware** [comment]
This is a known issue, and relates to how auto-detection works and interacts with the YAML parser that DDEV uses. You can definitely ignore this.

I'm not sure what happens if you specify an empty string, but if it does not cause trouble for you and makes the error disappear, that's fine.

**Comment by Furo42** [comment]
Yep, it doesn't cause any trouble to specify the variable as empty string.
Thanks for the information, I'll close this issue.
